// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FeaturedProductSection struct {
	ID       string     `json:"id"`
	Title    string     `json:"title"`
	Products []*Product `json:"products"`
}

func (FeaturedProductSection) IsEntity() {}

type Product struct {
	ID              string   `json:"id"`
	Name            string   `json:"name"`
	Brand           string   `json:"brand"`
	QuantityInStock int32    `json:"quantityInStock"`
	Price           float64  `json:"price"`
	Gallery         []string `json:"gallery"`
	Description     string   `json:"description"`
	Category        string   `json:"category"`
	Available       bool     `json:"available"`
}

func (Product) IsEntity() {}

type Query struct {
}
