package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"products-subgraph/data"
	"products-subgraph/graph/model"
)

// FeaturedProducts is the resolver for the featuredProducts field.
func (r *queryResolver) FeaturedProducts(ctx context.Context) ([]*model.FeaturedProductSection, error) {
	return data.FEATURED_PRODUCTS, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *featuredProductSectionResolver) Products(ctx context.Context, obj *model.FeaturedProductSection) ([]*model.Product, error) {
	return obj.Products, nil
}
func (r *Resolver) FeaturedProductSection() FeaturedProductSectionResolver { return &featuredProductSectionResolver{r} }
type featuredProductSectionResolver struct{ *Resolver }
*/
